persons:
  - email: abeveridge@varonis.com
    name: Beveridge Aaron
  - email: allen_aaron@intuit.com
    name: Allen Aaron
  - email: leah_abad@intuit.com
    name: Leah Abad
  - email: sabaray@hess.com
    name: Steven Abaray
  - email: abbott@csgi.com
    name: Karin Abbott
  - email: john.abdulmasih@ensighten.com
    name: John Abdul-Masih
  - email: deen_abdullah@intuit.com
    name: Deen Abdullah
  - email: k.abdullah@cequens.com
    name: Kareem Abdullah
  - email: rabel@landpoint.net
    name: Richard Abel
  - email: ryan.abel@autodesk.com
    name: Ryan Abel
  - email: stephen.abel@autodesk.com
    name: Stephen Abel
  - email: greg.aberle@flir.com
    name: Greg Aberle
  - email: mike@quickleft.com
    name: Mike AbiEzzi
  - email: tim.abla@autodesk.com
    name: Tim Abla
  - email: mike@bsmg.net
    name: Michael Abrahamson
  - email: abubakkar@ecolab.com
    name: Mohamed Abubakkar
  - email: sabukhodair@thomasnet.com
    name: Samir Abukhodair
  - email: mario_abundis@intuit.com
    name: Mario Abundis
  - email: bhakti_achlerkar@intuit.com
    name: Bhakti Achlerkar
  - email: terry@boomtownroi.com
    name: Terry Acker
  - email: jadam@overheaddoorofreading.com
    name: James Adam
  - email: jadams@countertack.com
    name: John Adams
  - email: jadams@presidio.com
    name: Jon Adams
  - email: john.adams@lightower.com
    name: John Adams
  - email: radams@hess.com
    name: Rick Adams
  - email: sean_adams@intuit.com
    name: Sean Adams
  - email: tony.adams@arqiva.com
    name: Tony Adams
  - email: ben.adderson@red-gate.com
    name: Ben Adderson
  - email: felix.adenodi@thomsonreuters.com
    name: Adedapo Adenodi
  - email: kadesoye@hess.com
    name: Kehinde Adesoye
  - email: irena.adler@lumenis.com
    name: Irena Adler
  - email: jaffrunti@advsyscon.com
    name: Joseph Affrunti
  - email: sagarwal@hess.com
    name: Saurabh Agarwal
  - email: magens@hess.com
    name: Mike Agens
  - email: charlesagnello@livenation.com
    name: Charles Agnello
  - email: ankur_agrawal@intuit.com
    name: Ankur Agrawal
  - email: rishabh_agrawal@intuit.com
    name: Rishabh Agrawal
  - email: aaguiar@axeda.com
    name: Andre Aguiar
  - email: mahmed@lightower.com
    name: Mumtaz Ahmed
  - email: shabir_ahmed@intuit.com
    name: Shabir Ahmed
  - email: usman@avanceon.com
    name: Usman Ahmed
  - email: charlesahn@livenation.com
    name: Charles Ahn
  - email: adam.ahrens@thomsonreuters.com
    name: Adam Ahrens
  - email: spring.ai@autodesk.com
    name: Spring Ai
  - email: pranav@conrep.com
    name: Pranav Ainavolu
  - email: adi.aizik@autodesk.com
    name: Adi Aizik
  - email: rakesh_ajmera@intuit.com
    name: Rakesh Ajmera
  - email: andrew.akenson@autodesk.com
    name: Andy Akenson
  - email: aakeze@hess.com
    name: Amaka Akeze
  - email: m.alawady@cequens.com
    name: Mohamed Al Awady
  - email: h.alaasar@cequens.com
    name: Hisham Al-Aasar
  - email: rizwan.alam@snapwiz.com
    name: Rizwan Alam
  - email: paland@presidio.com
    name: Patrick Aland
  - email: ahmed.alani@appliedis.com
    name: Ahmed Alani
  - email: sarah@uwm.edu
    name: Sarah Albertson
  - email: bdaldag@uwm.edu
    name: Bradley Aldag
  - email: miles.alden@ensighten.com
    name: Miles Alden
  - email: lalegria@flir.com
    name: Larry Alegria
  - email: romana@mirantis.com
    name: Roman Alekseenkov
  - email: al_aleman@intuit.com
    name: Al Aleman
  - email: salexander@accusoft.com
    name: Scot Alexander
  - email: juan-carlos.alfonso@autodesk.com
    name: Juan Carlos Alfonso
  - email: aali@habitat.org
    name: Abid Ali
  - email: ahsan.ali@autodesk.com
    name: Ahsan Ali
  - email: ali.demir@autodesk.com
    name: Demir Ali
  - email: mali@avanceon.com
    name: Mohammed Ali
  - email: shaheen.ali@arqiva.com
    name: Shaheen Ali
  - email: aaliberti@enernoc.com
    name: Antonio Aliberti
  - email: jacobalifrangis@livenation.com
    name: Jacob Alifrangis
  - email: madhavi_alikonda2@intuit.com
    name: Madhavi Alikonda
  - email: kenan_alkadi@intuit.com
    name: Kenan Alkadi
  - email: vani.alla@thomsonreuters.com
    name: Vani Alla
  - email: mallan@xyratex.com
    name: Mutaz Allan
  - email: mallen@presidio.com
    name: Mo Allen
  - email: verle_allen@intuit.com
    name: Verle Allen
  - email: wang.allen@autodesk.com
    name: Wang Allen
  - email: w.allis@maillsi.com
    name: Bill Allis
  - email: aballison@eiu.edu
    name: Aaron Allison
  - email: pooja.alluru@thomsonreuters.com
    name: Pooja Alluru
  - email: tim.allwardt@digitalinsight.com
    name: Tim Allwardt
  - email: malmanzor@xyratex.com
    name: Michael Almanzor
  - email: aalmomen@svsu.edu
    name: Ali AlMomen
  - email: jose.alonso@softtek.com
    name: Alfredo Alonso
  - email: fini@zmags.com
    name: Fini Alring
  - email: jalvarez@nexogy.com
    name: Jose Alvarez
  - email: jose_alvarez@intuit.com
    name: Jose Alvarez
  - email: davidamador@livenation.com
    name: David Amador
  - email: amodio.amato@arqiva.com
    name: Amodio Amato
  - email: matt.amdal@ecolab.com
    name: Matt Amdal
  - email: gautam.amin@ensighten.com
    name: Gautam Amin
  - email: mamin@advsyscon.com
    name: Mehul Amin
  - email: raminzia@presidio.com
    name: Rich Aminzia
  - email: nurit@varonis.com
    name: Nurit Amitai
  - email: susan.amkraut@autodesk.com
    name: Susan Amkraut
  - email: h.ammar@servicepower.com
    name: Hassan Ammar
  - email: sukhpreet.kaur@kayako.com
    name: Sukhpreet Anand
  - email: manaya@xyratex.com
    name: Miguel Anaya
  - email: janda@presidio.com
    name: Jose Anda
  - email: jesse.anderegg@lumenis.com
    name: Jesse Anderegg
  - email: dandersen@basho.com
    name: David Andersen
  - email: cmanderson@hess.com
    name: Clay Anderson
  - email: derricka@winntech.net
    name: Derrick Anderson
  - email: grahama@xyratex.com
    name: Graham Anderson
  - email: jason@meetmaestro.com
    name: Jason Anderson
  - email: neil.anderson@red-gate.com
    name: Neil Anderson
  - email: tanderson@presidio.com
    name: Thad Anderson
  - email: grega@slalom.com
    name: Greg Andonian
  - email: dennis_andreas@use.salvationarmy.org
    name: Dennis Andreas
  - email: derek_andrew@xyratex.com
    name: Derek Andrew
  - email: ken_andrews@intuit.com
    name: Ken Andrews
  - email: raymond.ang@autodesk.com
    name: Raymond Ang
  - email: cangel@presidio.com
    name: Charles Angel
  - email: dangot@atlassian.com
    name: David Angot
  - email: danny.angus@openbet.com
    name: Danny Angus
  - email: dharani.animireddy@thomsonreuters.com
    name: Dharani Animireddy
  - email: gurupraveen.annadanappa@thomsonreuters.com
    name: Gurupraveen Annadanappa
  - email: mark.ansley@rmgnetworks.com
    name: Mark Ansley
  - email: ranthony@presidio.com
    name: Roy Anthony
  - email: josh@ektron.com
    name: Josh Apgar
  - email: sujatha_appalanaidu@xyratex.com
    name: Sujatha Appalanaidu
  - email: cheryl_aranha@intuit.com
    name: Cheryl Aranha
  - email: baraujo@thomasnet.com
    name: Bruno Araujo
  - email: adam.arbree@autodesk.com
    name: Adam Arbree
  - email: carchibeque@hess.com
    name: Carla Archibeque
  - email: jarduini@xtivia.com
    name: Jan Arduini
  - email: stevena@slalom.com
    name: Steven Arevalo
  - email: jargento@accusoft.com
    name: Joseph Argento
  - email: kathy.arizon@autodesk.com
    name: Kathy Arizon
  - email: darlow@chemtreat.com
    name: Doug Arlow
  - email: jima@zillow.com
    name: Jim Arment
  - email: eric.arnaez@universalwilde.com
    name: Eric Arnaez
  - email: paul-henri.arnaud@autodesk.com
    name: Paul-Henri Arnaud
  - email: christopher.arnold@ecolab.com
    name: Chris Arnold
  - email: joe_arnold@intuit.com
    name: Joe Arnold
  - email: warojado@presidio.com
    name: Wally Arojado
  - email: david.aronson@flir.com
    name: David Aronson
  - email: sumit@infochimps.com
    name: Sumit Arrawatia
  - email: kojo.arthurmensah@ecolab.com
    name: Kojo Arthur-Mensah
  - email: marvin.artiaga@thomsonreuters.com
    name: Marvin Artiaga
  - email: brian.arvidson@avella.com
    name: Brian Arvidson
  - email: pat_arvin@intuit.com
    name: Patrick Arvin
  - email: apurva_asarawala@intuit.com
    name: Apurva Asarawala
  - email: saschettino@imprivata.com
    name: Steve Aschettino
  - email: fashby@hess.com
    name: Frank Ashby
  - email: russella@slalom.com
    name: Russell Asher
  - email: bashley@impinj.com
    name: Bill Ashley
  - email: bhavya.ashwatha@thomsonreuters.com
    name: Bhavya Ashwatha
  - email: michael.ashworth@autodesk.com
    name: Michael Ashworth
  - email: jaslakson@sonicbids.com
    name: Jason Aslakson
  - email: christopher.aspromgos@thomsonreuters.com
    name: Cj Aspromgos
  - email: pouyan_assadi@intuit.com
    name: Pouyan Assadi
  - email: hideto.atago@autodesk.com
    name: Hideto Atago
  - email: catchley@novacoast.com
    name: Chris Atchley
  - email: evan-atherton@autodesk.com
    name: Evan Atherton
  - email: mark.atkins@arqiva.com
    name: Mark Atkins
  - email: richard@atlassian.com
    name: Richard Atkins
  - email: marc_attinasi@intuit.com
    name: Marc Attinasi
  - email: barak@varonis.com
    name: Barak Attiya
  - email: joel_atwood@intuit.com
    name: Joel Atwood
  - email: shawn.auger@ecolab.com
    name: Shawn Auger
  - email: aaugot@axeda.com
    name: Alex Augot
  - email: brian_ault@intuit.com
    name: Brian Ault
  - email: sithu_aung@intuit.com
    name: Sithu Aung
  - email: maxa@slalom.com
    name: Max Aussendorf
  - email: maustin@hess.com
    name: Michael Austin
  - email: larry_austria@intuit.com
    name: Larry Austria
  - email: arun_avanathan@intuit.com
    name: Arun Avanathan
  - email: ufuk.avci@basho.com
    name: Ufuk Avci
  - email: freddy.avendano@autodesk.com
    name: Freddy Avendano
  - email: aavila@presidio.com
    name: Andres Avila
  - email: stephen.axelsen@arqiva.com
    name: Stephen Axelsen
  - email: mihir_ayachit@intuit.com
    name: Mihir Ayachit
  - email: arjun.ayyar@autodesk.com
    name: Arjun Ayyar
  - email: mazeem@servicepower.com
    name: Mohammed Azeem
  - email: omer_azmon@intuit.com
    name: Omer Azmon
  - email: blake@cpfd-software.com
    name: Blake Azuela
  - email: marwan.azzam@autodesk.com
    name: Marwan Azzam
  - email: brandon.baardman@thomsonreuters.com
    name: Brandon Baardman
  - email: meghan.babcock@ecolab.com
    name: Meghan Babcock
  - email: madhu_babu@intuit.com
    name: Madhu Babu
  - email: narendra_babu@intuit.com
    name: Narendra Babu
  - email: vijay_babu@intuit.com
    name: Vijay Babu
  - email: matthew.bacalakis@thomsonreuters.com
    name: Matthew Bacalakis
  - email: abacik@ss8.com
    name: Alex Bacik
  - email: dbackeris@presidio.com
    name: Dean Backeris
  - email: anthony_bacoy@intuit.com
    name: Anthony Bacoy
  - email: vinayakb@slalom.com
    name: Vinayak Badrinathan
  - email: jbahou@indium.com
    name: Joe Bahou
  - email: brandonb@slalom.com
    name: Brandon Bailey
  - email: len.bainbridge@ecolab.com
    name: Len Bainbridge
  - email: abel_bak@xyratex.com
    name: Abel Bak
  - email: abaker@useartisan.com
    name: Alec Baker
  - email: bobaker@hess.com
    name: Robert Baker
  - email: john.baker@ecolab.com
    name: John Baker
  - email: alex.bakharev@autodesk.com
    name: Alexander Bakharev
  - email: johar_bakri@xyratex.com
    name: Johar Bakri
  - email: tbal@thomasnet.com
    name: Timothy Bal
  - email: lakshmi_balakrishna@intuit.com
    name: Lakshmi Balakrishna
  - email: cbaldwin@hess.com
    name: Carlos Baldwin
  - email: stephen_baldwin@csgi.com
    name: Stephen Baldwin